apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
  template:
    metadata:
      name: myjavaapp
      labels:
        app: myjavaapp
        version: 2.6.2
    spec:
      containers:
      - name: myjavaapp-container
        image: maha4iac/mahalogin:1
        ports: 
        - containerPort: 8080